version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: productservice
      POSTGRES_PASSWORD: productservicepassword
      POSTGRES_DB: productfiles
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productfiles
      SPRING_DATASOURCE_USERNAME: productservice
      SPRING_DATASOURCE_PASSWORD: productservicepassword

volumes:
  postgres-data: